version: '3.8'

services:
  client:
    build:
      context: ./infra/docker
      dockerfile: client.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://server:5000/api
    networks:
      - wiki-network

  server:
    build:
      context: ./infra/docker
      dockerfile: server.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://user:password@db:3306/wiki
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - db
    networks:
      - wiki-network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wiki
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wiki-network

networks:
  wiki-network:
    driver: bridge

volumes:
  db_data: